"""
Static task data: tickets + ground truth for all 4 tasks.
Scores are always strictly in (0.01, 0.99) — never 0.0 or 1.0.
"""
from __future__ import annotations
from typing import Any, Dict, List

# ── EASY: 5 tickets, classify only ───────────────────────────────────────────
EASY_TICKETS: List[Dict[str, Any]] = [
    {"id": "T001", "subject": "Charged twice on my invoice",
     "body": "I see two charges of $49.99 on Oct 3rd — I only made one purchase. Please refund the duplicate immediately.",
     "customer_name": "Alice Chen", "customer_email": "alice@email.com",
     "created_at": "2024-10-03T09:15:00Z", "ticket_metadata": {}},
    {"id": "T002", "subject": "Password reset email not received",
     "body": "Forgot my password and the reset email never arrived. Checked spam too. Need help getting back in.",
     "customer_name": "Bob Smith", "customer_email": "bob@email.com",
     "created_at": "2024-10-03T10:00:00Z", "ticket_metadata": {}},
    {"id": "T003", "subject": "Defective product — screen flickers and dies",
     "body": "Order #ORD-8821 stopped working after two days. Screen flickers then goes black. Want a replacement or refund.",
     "customer_name": "Carol Davis", "customer_email": "carol@email.com",
     "created_at": "2024-10-03T11:30:00Z", "ticket_metadata": {}},
    {"id": "T004", "subject": "App crashes every time I open Reports on iPhone",
     "body": "Crashes on iPhone 14, iOS 17.0.3 in the Reports section. Reinstalled twice. Blocking my work — urgent.",
     "customer_name": "David Lee", "customer_email": "david@email.com",
     "created_at": "2024-10-03T12:00:00Z", "ticket_metadata": {}},
    {"id": "T005", "subject": "What are your support hours?",
     "body": "Quick question — what are your customer support hours? Do you have weekend coverage?",
     "customer_name": "Emma Wilson", "customer_email": "emma@email.com",
     "created_at": "2024-10-03T13:00:00Z", "ticket_metadata": {}},
]
EASY_GT: Dict[str, Dict[str, str]] = {
    "T001": {"department": "billing",   "urgency": "high"},
    "T002": {"department": "technical", "urgency": "medium"},
    "T003": {"department": "returns",   "urgency": "medium"},
    "T004": {"department": "technical", "urgency": "high"},
    "T005": {"department": "general",   "urgency": "low"},
}

# ── MEDIUM: 3 tickets, respond ────────────────────────────────────────────────
MEDIUM_TICKETS: List[Dict[str, Any]] = [
    {"id": "M001", "subject": "Cancelled subscription but still charged",
     "body": "Cancelled Premium on Sep 15th, got confirmation, but charged $29.99 on Oct 1st. Need refund and no further charges. Account: frank@email.com",
     "customer_name": "Frank Jones", "customer_email": "frank@email.com",
     "created_at": "2024-10-02T08:00:00Z",
     "ticket_metadata": {"subscription_id": "SUB-4421", "plan": "Premium"}},
    {"id": "M002", "subject": "CSV export returns error 500 — deadline tomorrow",
     "body": "Every time I click Export I get error 500. Client presentation tomorrow morning. Tried Chrome, Firefox, Edge.",
     "customer_name": "Grace Kim", "customer_email": "grace@email.com",
     "created_at": "2024-10-02T14:30:00Z",
     "ticket_metadata": {"error_code": "500", "browsers": ["Chrome", "Firefox", "Edge"]}},
    {"id": "M003", "subject": "Order arrived damaged — need replacement",
     "body": "Order ORD-9934 arrived with box crushed and product cracked. Paid $89.99. Want replacement or full refund. I have photos.",
     "customer_name": "Henry Park", "customer_email": "henry@email.com",
     "created_at": "2024-10-02T16:00:00Z",
     "ticket_metadata": {"order_id": "ORD-9934", "amount": 89.99}},
]
MEDIUM_CRITERIA: Dict[str, Dict[str, Any]] = {
    "M001": {"keywords": ["refund", "apologize", "cancel", "charge"], "min_words": 80,
             "ack_phrases": ["sorry", "apologize", "understand"],
             "action_phrases": ["refund", "process", "team", "resolve"]},
    "M002": {"keywords": ["export", "error", "workaround", "team"], "min_words": 80,
             "ack_phrases": ["sorry", "apologize", "understand", "urgent"],
             "action_phrases": ["investigate", "engineer", "workaround", "fix", "team"]},
    "M003": {"keywords": ["replacement", "refund", "apologize", "damage"], "min_words": 80,
             "ack_phrases": ["sorry", "apologize", "understand"],
             "action_phrases": ["replacement", "refund", "arrange", "team", "send"]},
}

# ── HARD: 8 tickets, full triage ─────────────────────────────────────────────
HARD_TICKETS: List[Dict[str, Any]] = [
    {"id": "H001", "subject": "URGENT: Production API 403 for all requests",
     "body": "Entire production system down since 2AM UTC. All API calls return 403 Forbidden. API key regenerated twice. P0 incident.",
     "customer_name": "Iris Thompson", "customer_email": "iris@acme.com",
     "created_at": "2024-10-04T02:15:00Z", "ticket_metadata": {"plan": "Enterprise", "mrr": 5000}},
    {"id": "H002", "subject": "Win a $1000 gift card!",
     "body": "You've been selected to win $1000! Click: http://suspicious-site.xyz/claim",
     "customer_name": "Unknown Sender", "customer_email": "noreply@suspicious-site.xyz",
     "created_at": "2024-10-04T03:00:00Z", "ticket_metadata": {}},
    {"id": "H003", "subject": "Upgrade from monthly to annual billing",
     "body": "Currently on monthly Pro plan, want to switch to annual. Is there a pro-rated credit for remaining days?",
     "customer_name": "James Nguyen", "customer_email": "james@email.com",
     "created_at": "2024-10-04T09:00:00Z", "ticket_metadata": {"plan": "Pro Monthly"}},
    {"id": "H004", "subject": "2FA SMS codes never arrive — locked out",
     "body": "Set up 2FA last week, now locked out because SMS codes never arrive. Phone number is correct. Completely stuck.",
     "customer_name": "Kate Morris", "customer_email": "kate@email.com",
     "created_at": "2024-10-04T09:30:00Z", "ticket_metadata": {}},
    {"id": "H005", "subject": "GDPR Article 17 — delete all my data",
     "body": "Formally requesting deletion of all personal data under GDPR Article 17. Account: liam@email.com. Confirm in 30 days or I'll file ICO complaint.",
     "customer_name": "Liam Brown", "customer_email": "liam@email.com",
     "created_at": "2024-10-04T10:00:00Z", "ticket_metadata": {"legal": True}},
    {"id": "H006", "subject": "Wrong item in my order ORD-7751",
     "body": "Ordered Blue Widget (BW-100) but received Red Widget (RW-200). Packing slip correct but box wrong. Please arrange collection and send correct item.",
     "customer_name": "Mia Clark", "customer_email": "mia@email.com",
     "created_at": "2024-10-04T10:30:00Z", "ticket_metadata": {"order_id": "ORD-7751"}},
    {"id": "H007", "subject": "Love the product — filter suggestion",
     "body": "Your product saves me hours every week! Small suggestion: dashboard should remember last used filter. Keep up the great work!",
     "customer_name": "Noah Adams", "customer_email": "noah@email.com",
     "created_at": "2024-10-04T11:00:00Z", "ticket_metadata": {"sentiment": "positive"}},
    {"id": "H008", "subject": "Can't download receipts — PDF button does nothing",
     "body": "Billing portal shows invoices but clicking Download PDF does nothing. Need for expense report by Friday. Chrome on Windows 11.",
     "customer_name": "Olivia Scott", "customer_email": "olivia@email.com",
     "created_at": "2024-10-04T11:30:00Z", "ticket_metadata": {}},
]
HARD_GT: Dict[str, Dict[str, Any]] = {
    "H001": {"department": "technical", "urgency": "high",  "action": "escalate",
             "reason_kws": ["p0", "production", "outage", "enterprise", "urgent"]},
    "H002": {"department": "general",   "urgency": "low",   "action": "archive",
             "reason_kws": ["spam", "phishing", "suspicious", "scam"]},
    "H003": {"department": "billing",   "urgency": "low",   "action": "respond",
             "response_kws": ["annual", "upgrade", "credit", "pro-rat", "billing"]},
    "H004": {"department": "technical", "urgency": "high",  "action": "respond",
             "response_kws": ["2fa", "locked", "sms", "alternative", "verify"]},
    "H005": {"department": "general",   "urgency": "high",  "action": "escalate",
             "reason_kws": ["gdpr", "legal", "compliance", "deletion", "data"]},
    "H006": {"department": "returns",   "urgency": "medium","action": "respond",
             "response_kws": ["wrong", "collect", "correct", "replacement", "apologize"]},
    "H007": {"department": "general",   "urgency": "low",   "action": "close",
             "response_kws": ["thank", "feedback", "feature", "team"]},
    "H008": {"department": "technical", "urgency": "medium","action": "respond",
             "response_kws": ["pdf", "download", "browser", "investigate", "workaround"]},
}

# ── EXPERT: 10 churn-risk tickets ────────────────────────────────────────────
EXPERT_TICKETS: List[Dict[str, Any]] = [
    {"id": "E001", "subject": "Competitor offering 40% less — contract renews next month",
     "body": "3-year customer here. CompetitorX offered 40% less. Contract renews in 30 days. Need to justify cost to my CFO. Can you do anything? — Sarah, Acme Corp",
     "customer_name": "Sarah Mitchell", "customer_email": "sarah@acmecorp.com",
     "created_at": "2024-10-05T09:00:00Z",
     "ticket_metadata": {"plan": "Enterprise", "mrr": 4200, "tenure_months": 36, "ltv": 151200}},
    {"id": "E002", "subject": "Bulk-export API being deprecated — our workflow breaks",
     "body": "Saw the deprecation notice for bulk-export API. We run 200+ exports per week. If no alternative, we'll find another solution. Urgent.",
     "customer_name": "Tom Bradley", "customer_email": "tom@techstartup.io",
     "created_at": "2024-10-05T09:15:00Z",
     "ticket_metadata": {"plan": "Pro", "mrr": 890, "tenure_months": 14}},
    {"id": "E003", "subject": "5th outage this month — costing us $5k each time",
     "body": "Fifth platform outage this month during business hours. $5,000 lost productivity each time. Enterprise customer expecting SLA. Requesting credit and RCA. If reliability doesn't improve, we'll explore alternatives.",
     "customer_name": "Jennifer Walsh", "customer_email": "jennifer@globalfinance.com",
     "created_at": "2024-10-05T10:00:00Z",
     "ticket_metadata": {"plan": "Enterprise Plus", "mrr": 8500, "tenure_months": 24, "ltv": 204000}},
    {"id": "E004", "subject": "How do I export all my data?",
     "body": "Planning to evaluate some alternatives over the next few weeks. Can you tell me how to export everything — settings, history, user profiles? Want to make sure I have a backup.",
     "customer_name": "Marcus Chen", "customer_email": "marcus@designstudio.co",
     "created_at": "2024-10-05T10:30:00Z",
     "ticket_metadata": {"plan": "Team", "mrr": 450, "tenure_months": 8}},
    {"id": "E005", "subject": "Still charged for 8 deactivated seats — $960 wasted",
     "body": "Deactivated 8 seats in July, still being charged $320/month × 3 months = $960. Raised before with no resolution. Really frustrating — questioning whether to continue.",
     "customer_name": "Priya Sharma", "customer_email": "priya@consulting.in",
     "created_at": "2024-10-05T11:00:00Z",
     "ticket_metadata": {"plan": "Business", "mrr": 1200, "tenure_months": 19}},
    {"id": "E006", "subject": "New CEO consolidating from 45 to 20 SaaS tools — need ROI case",
     "body": "CEO mandated SaaS audit. Need to justify keeping your product. Can you provide ROI data, case studies from similar companies, unique features vs alternatives? Decision deadline end of month.",
     "customer_name": "Alex Rivera", "customer_email": "alex@manufacturing.com",
     "created_at": "2024-10-05T11:30:00Z",
     "ticket_metadata": {"plan": "Enterprise", "mrr": 3600, "tenure_months": 41, "ltv": 147600}},
    {"id": "E007", "subject": "Team downsized from 12 to 2 — paying for unused seats",
     "body": "Started with 12 people, now just 2. Paying for 10 unused seats. Is there a smaller plan? Love the product but can't justify current cost.",
     "customer_name": "Lisa Park", "customer_email": "lisa@freelance.net",
     "created_at": "2024-10-05T12:00:00Z",
     "ticket_metadata": {"plan": "Team 10", "mrr": 290, "tenure_months": 22}},
    {"id": "E008", "subject": "Salesforce integration breaks every 10 days — sales team frustrated",
     "body": "Salesforce integration has broken 4 times in 6 weeks. Each time we get a workaround, not a real fix. Sales team manually re-entering data. Need permanent fix or we'll find a tool that works.",
     "customer_name": "David Okonkwo", "customer_email": "david@salespartner.com",
     "created_at": "2024-10-05T13:00:00Z",
     "ticket_metadata": {"plan": "Business", "mrr": 1800, "tenure_months": 11}},
    {"id": "E009", "subject": "Renewing for sure — is there a 2-year discount?",
     "body": "Contract up next week and we're definitely staying — the product has been fantastic. Quick question: is there a multi-year discount for a 2-year commitment?",
     "customer_name": "Rachel Kim", "customer_email": "rachel@healthtech.io",
     "created_at": "2024-10-05T13:30:00Z",
     "ticket_metadata": {"plan": "Enterprise", "mrr": 2900, "tenure_months": 18}},
    {"id": "E010", "subject": "Security audit flagged missing SOC 2 Type II — healthcare compliance risk",
     "body": "Security audit flagged no SOC 2 Type II certification. We're in healthcare (regulated). Compliance team says we may not be able to continue. Can you provide compliance docs? Board meeting in 2 weeks.",
     "customer_name": "Dr. James Thornton", "customer_email": "j.thornton@medicalgroup.org",
     "created_at": "2024-10-05T14:00:00Z",
     "ticket_metadata": {"plan": "Enterprise Plus", "mrr": 6200, "tenure_months": 7}},
]
EXPERT_GT: Dict[str, Dict[str, Any]] = {
    "E001": {"department": "billing",   "urgency": "high",   "churn_risk": "critical", "action": "escalate",
             "reason_kws": ["competitor", "price", "retention", "enterprise", "renewal"],
             "response_kws": ["value", "offer", "discount", "loyalty", "appreciate"]},
    "E002": {"department": "technical", "urgency": "high",   "churn_risk": "high",     "action": "respond",
             "response_kws": ["alternative", "migration", "deprecation", "api", "workflow", "export"]},
    "E003": {"department": "technical", "urgency": "high",   "churn_risk": "critical", "action": "escalate",
             "reason_kws": ["outage", "sla", "enterprise", "reliability", "credit"],
             "response_kws": ["credit", "sla", "root cause", "apologize", "reliability"]},
    "E004": {"department": "general",   "urgency": "high",   "churn_risk": "high",     "action": "respond",
             "response_kws": ["export", "data", "help", "stay", "value", "alternative"]},
    "E005": {"department": "billing",   "urgency": "high",   "churn_risk": "high",     "action": "respond",
             "response_kws": ["refund", "credit", "apologize", "seat", "resolve", "billing"]},
    "E006": {"department": "general",   "urgency": "high",   "churn_risk": "critical", "action": "escalate",
             "reason_kws": ["ceo", "roi", "consolidation", "business case", "enterprise"],
             "response_kws": ["roi", "case study", "value", "feature", "business"]},
    "E007": {"department": "billing",   "urgency": "medium", "churn_risk": "medium",   "action": "respond",
             "response_kws": ["plan", "downgrade", "seats", "cost", "option", "smaller"]},
    "E008": {"department": "technical", "urgency": "high",   "churn_risk": "high",     "action": "escalate",
             "reason_kws": ["salesforce", "integration", "breaking", "productivity", "permanent"],
             "response_kws": ["integration", "fix", "engineer", "salesforce", "priority"]},
    "E009": {"department": "billing",   "urgency": "low",    "churn_risk": "low",      "action": "respond",
             "response_kws": ["discount", "annual", "multi-year", "thank", "loyalty", "renew"]},
    "E010": {"department": "general",   "urgency": "high",   "churn_risk": "critical", "action": "escalate",
             "reason_kws": ["compliance", "soc2", "healthcare", "security", "regulated"],
             "response_kws": ["compliance", "soc2", "security", "documentation", "certif"]},
}

TASKS_META = {
    "ticket_classification": {
        "tickets": EASY_TICKETS, "gt": EASY_GT,
        "difficulty": "easy", "max_steps": 10, "num_tickets": 5,
        "description": "Classify 5 support tickets by department and urgency.",
    },
    "ticket_response": {
        "tickets": MEDIUM_TICKETS, "gt": MEDIUM_CRITERIA,
        "difficulty": "medium", "max_steps": 9, "num_tickets": 3,
        "description": "Draft professional responses to 3 support tickets.",
    },
    "inbox_triage": {
        "tickets": HARD_TICKETS, "gt": HARD_GT,
        "difficulty": "hard", "max_steps": 24, "num_tickets": 8,
        "description": "Full 8-ticket inbox: classify, escalate, respond, archive.",
    },
    "churn_prevention": {
        "tickets": EXPERT_TICKETS, "gt": EXPERT_GT,
        "difficulty": "expert", "max_steps": 30, "num_tickets": 10,
        "description": "10 high-value at-risk customers — detect churn, personalise retention.",
    },
}
